// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// OptimizeBIC
S4 OptimizeBIC(S4 reference);
RcppExport SEXP ClustOrd_OptimizeBIC(SEXP referenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    __result = Rcpp::wrap(OptimizeBIC(reference));
    return __result;
END_RCPP
}
